{
 "title": "Hardware inventory",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})",
       "legendFormat": "CPUs"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"memory\"}) / 1024^3",
       "legendFormat": "CPU memory (GB)"
      },
      { "expr": "count(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "GPUs" },
      {
       "expr": "sum(DCGM_FI_DEV_FB_FREE + DCGM_FI_DEV_FB_USED) / 1024",
       "legendFormat": "GPU memory (GB)"
      }
     ]
    }
   ]
  },
  {
   "title": "Number CPUs/GPUs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPUs per node",
     "type": "bargauge",
     "gridPos": { "h": 23, "w": 11, "x": 0, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_node_status_capacity{resource=\"cpu\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "GPUs per node",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 12, "x": 11, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(Hostname) (DCGM_FI_DEV_GPU_UTIL)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU memory (GB)",
     "type": "bargauge",
     "gridPos": { "h": 23, "w": 10, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_node_status_capacity{resource=\"memory\"} / 1024^3",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "GPU memory (GB)",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 9, "x": 10, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(Hostname) ((DCGM_FI_DEV_FB_FREE + DCGM_FI_DEV_FB_USED) / 1024)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU model names",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "node :: model",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 17, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(Hostname, modelName) (DCGM_FI_DEV_FB_FREE)",
       "legendFormat": "{{Hostname}} :: {{modelName}}"
      }
     ]
    }
   ]
  }
 ]
}