{
 "title": "Ceph - Multi-cluster",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_health_status==0) or vector(0)",
     "legendFormat": "Healthy"
    },
    { "expr": "count(ceph_health_status==1)", "legendFormat": "Warning" },
    { "expr": "count(ceph_health_status==2)", "legendFormat": "Error" }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 2 },
   "targets": [
    { "expr": "ceph_health_status", "legendFormat": "__auto" },
    { "expr": "ceph_mgr_metadata", "legendFormat": "__auto" },
    {
     "expr": "count(ALERTS{alertstate=\"firing\", cluster=~\"$cluster|\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceph_cluster_by_class_total_used_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cluster Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_health_status{cluster=~\"$cluster|\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_bytes{cluster=~\"$cluster|\"}) / sum(ceph_cluster_total_bytes{cluster=~\"$cluster|\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_bytes{cluster=~\"$cluster|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_metadata{cluster=~\"$cluster|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (hostname) (ceph_osd_metadata{cluster=~\"$cluster|\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client IOPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr{cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(ceph_pool_rd{cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "OSD Latencies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{cluster=~\"$cluster|\"})",
     "legendFormat": "Apply"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{cluster=~\"$cluster|\"})",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "title": "Alert Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", cluster=~\"$cluster|\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_bytes{cluster=~\"$cluster|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity Prediction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "predict_linear(avg(increase(ceph_cluster_total_used_bytes{cluster=~\"${Cluster}\"}[1d]))[7d:1h],120)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_pool_metadata{cluster=~\"$cluster|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd_bytes{cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(ceph_pool_wr_bytes{cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Recovery Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_recovery_ops{cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\",severity=\"critical\", cluster=~\"$cluster|\"}) OR vector(0)",
       "legendFormat": "Critical"
      },
      {
       "expr": "count(ALERTS{alertstate=\"firing\",severity=\"warning\", cluster=~\"$cluster|\"}) OR vector(0)",
       "legendFormat": "Warning"
      }
     ]
    },
    {
     "title": "Alerts",
     "type": "table",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 19 },
     "targets": [
      {
       "expr": "ALERTS{alertstate=\"firing\", cluster=~\"$cluster|\", }",
       "legendFormat": "__auto"
      }
     ]
    },
    { "title": "Alerts(Grouped)", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 } }
   ]
  },
  {
   "title": "Cluster Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 - Capacity Utilization(%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(5, ceph_cluster_total_used_bytes/ceph_cluster_total_bytes)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Top 5 - Cluster IOPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(10, sum by (cluster) (rate(ceph_osd_op_w[$__rate_interval]))  \n+ sum by (cluster) (rate(ceph_osd_op_r[$__rate_interval])) )",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Top 10 - Capacity Utilization(%) by Pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(10, ceph_pool_bytes_used{cluster=~\"$cluster|\", }/ceph_pool_max_avail{cluster=~\"$cluster|\", } * on(pool_id, cluster) group_left(instance, name) ceph_pool_metadata{cluster=~\"$cluster|\", })",
       "legendFormat": "{{cluster}} - {{name}}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "OSD device details",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "osd",
    "label": "OSD",
    "query": "label_values(ceph_osd_metadata{cluster=~\"$cluster|\", }, ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "OSD Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$osd Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_latency_sum{ceph_daemon=~\"$osd\", cluster=~\"$cluster|\", }[$__rate_interval]) /\n  on (ceph_daemon) rate(ceph_osd_op_r_latency_count{cluster=~\"$cluster|\", }[$__rate_interval])\n",
     "legendFormat": "read"
    },
    {
     "expr": "rate(ceph_osd_op_w_latency_sum{ceph_daemon=~\"$osd\", cluster=~\"$cluster|\", }[$__rate_interval]) /\n  on (ceph_daemon) rate(ceph_osd_op_w_latency_count{cluster=~\"$cluster|\", }[$__rate_interval])\n",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "$osd R/W IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r{ceph_daemon=~\"$osd\", cluster=~\"$cluster|\", }[$__rate_interval])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(ceph_osd_op_w{ceph_daemon=~\"$osd\", cluster=~\"$cluster|\", }[$__rate_interval])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "$osd R/W Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_out_bytes{ceph_daemon=~\"$osd\", cluster=~\"$cluster|\", }[$__rate_interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(ceph_osd_op_w_in_bytes{ceph_daemon=~\"$osd\", cluster=~\"$cluster|\", }[$__rate_interval])",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  { "title": "Physical Device Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Physical Device Latency for $osd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  label_replace(\n    rate(node_disk_read_time_seconds_total[$__rate_interval]) /\n      rate(node_disk_reads_completed_total[$__rate_interval]),\n    \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n  ) and on (instance, device) label_replace(\n    label_replace(\n      ceph_disk_occupation_human{ceph_daemon=~\"$osd\", cluster=~\"$cluster|\", },\n      \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n    ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n  )\n)\n",
     "legendFormat": "{{instance}}/{{device}} Reads"
    },
    {
     "expr": "(\n  label_replace(\n    rate(node_disk_write_time_seconds_total[$__rate_interval]) /\n      rate(node_disk_writes_completed_total[$__rate_interval]),\n    \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") and on (instance, device)\n    label_replace(\n      label_replace(\n        ceph_disk_occupation_human{ceph_daemon=~\"$osd\", cluster=~\"$cluster|\", }, \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n      ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n    )\n)\n",
     "legendFormat": "{{instance}}/{{device}} Writes"
    }
   ]
  },
  {
   "title": "Physical Device R/W IOPS for $osd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n  rate(node_disk_writes_completed_total[$__rate_interval]),\n  \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{ceph_daemon=~\"$osd\", cluster=~\"$cluster|\", },\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}} on {{instance}} Writes"
    },
    {
     "expr": "label_replace(\n  rate(node_disk_reads_completed_total[$__rate_interval]),\n  \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{ceph_daemon=~\"$osd\", cluster=~\"$cluster|\", },\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}} on {{instance}} Reads"
    }
   ]
  },
  {
   "title": "Physical Device R/W Bytes for $osd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(\n  rate(node_disk_read_bytes_total[$__rate_interval]), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{ceph_daemon=~\"$osd\", cluster=~\"$cluster|\", },\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{instance}} {{device}} Reads"
    },
    {
     "expr": "label_replace(\n  rate(node_disk_written_bytes_total[$__rate_interval]), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{ceph_daemon=~\"$osd\", cluster=~\"$cluster|\", },\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{instance}} {{device}} Writes"
    }
   ]
  },
  {
   "title": "Physical Device Util% for $osd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  rate(node_disk_io_time_seconds_total[$__rate_interval]),\n  \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{ceph_daemon=~\"$osd\", cluster=~\"$cluster|\", }, \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}} on {{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "Ceph Cluster - Advanced",
 "description": "Ceph cluster overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ceph health status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_health_status{cluster=~\"$cluster|\", }"
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes{cluster=~\"$cluster|\", }-ceph_cluster_total_used_bytes{cluster=~\"$cluster|\", })/ceph_cluster_total_bytes{cluster=~\"$cluster|\", }"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{cluster=~\"$cluster|\", }"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_w_in_bytes{cluster=~\"$cluster|\", }[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_r_out_bytes{cluster=~\"$cluster|\", }[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_osd_metadata{cluster=~\"$cluster|\", })",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "In",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in{cluster=~\"$cluster|\", })",
     "legendFormat": "In",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Out",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in{cluster=~\"$cluster|\", } == bool 0)",
     "legendFormat": "Out",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{cluster=~\"$cluster|\", })",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{cluster=~\"$cluster|\", } == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "MGRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Active",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mgr_status{cluster=~\"$cluster|\", } == 1) or vector(0)",
     "legendFormat": "Active",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Standby",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mgr_status{cluster=~\"$cluster|\", } == 0) or vector(0)",
     "legendFormat": "Standby",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Active",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ALERTS{alertstate=\"firing\",alertname=~\"^Ceph.+\", severity=\"critical\", cluster=~\"$cluster|\", }) OR vector(0)",
     "legendFormat": "Critical",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Standby",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ALERTS{alertstate=\"firing\",alertname=~\"^Ceph.+\", severity=\"warning\", cluster=~\"$cluster|\", }) OR vector(0)",
     "legendFormat": "Warning",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{cluster=~\"$cluster|\", }"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_w{cluster=~\"$cluster|\", }[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_r{cluster=~\"$cluster|\", }[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "In Quorum",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_mon_quorum_status{cluster=~\"$cluster|\", })",
     "legendFormat": "In Quorum",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "Total",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mon_quorum_status{cluster=~\"$cluster|\", })",
     "legendFormat": "Total",
     "units": "none",
     "valueHandler": "Text Only",
     "warn": 2
    },
    {
     "aggregation": "Last",
     "alias": "MONs out of Quorum",
     "crit": 1.6,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "Never",
     "expr": "count(ceph_mon_quorum_status{cluster=~\"$cluster|\", }) - sum(ceph_mon_quorum_status{cluster=~\"$cluster|\", })",
     "legendFormat": "MONs out of Quorum",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1.1
    }
   ]
  },
  { "title": "CLUSTER STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 } },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{cluster=~\"$cluster|\", }",
     "legendFormat": "Total Capacity"
    },
    {
     "expr": "ceph_cluster_total_used_bytes{cluster=~\"$cluster|\", }",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Cluster Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_w_in_bytes{cluster=~\"$cluster|\", }[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(ceph_osd_op_r_out_bytes{cluster=~\"$cluster|\", }[$__rate_interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_w{cluster=~\"$cluster|\", }[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(ceph_osd_op_r{cluster=~\"$cluster|\", }[$__rate_interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Pool Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_bytes_used{cluster=~\"$cluster|\", }) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster=~\"$cluster|\", })",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Used RAW Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_stored_raw{cluster=~\"$cluster|\", }) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster=~\"$cluster|\", })",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Objects Quota",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_objects{cluster=~\"$cluster|\", }) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster=~\"$cluster|\", })",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Quota Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_bytes{cluster=~\"$cluster|\", }) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster=~\"$cluster|\", })",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Objects Per Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_objects{cluster=~\"$cluster|\", }) * on (pool_id) group_left(name)(ceph_pool_metadata{cluster=~\"$cluster|\", })",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "OSD Type Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_objects{cluster=~\"$cluster|\", })",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PGs State",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pg_active{cluster=~\"$cluster|\", })",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(ceph_pg_clean{cluster=~\"$cluster|\", })",
     "legendFormat": "Clean"
    },
    {
     "expr": "sum(ceph_pg_peering{cluster=~\"$cluster|\", })",
     "legendFormat": "Peering"
    },
    {
     "expr": "sum(ceph_pg_degraded{cluster=~\"$cluster|\", })",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{cluster=~\"$cluster|\", })",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_unclean_pgs{cluster=~\"$cluster|\", })",
     "legendFormat": "Unclean"
    },
    {
     "expr": "sum(ceph_pg_undersized{cluster=~\"$cluster|\", })",
     "legendFormat": "Undersized"
    },
    {
     "expr": "sum(ceph_pg_incomplete{cluster=~\"$cluster|\", })",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "sum(ceph_pg_forced_backfill{cluster=~\"$cluster|\", })",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "sum(ceph_pg_forced_recovery{cluster=~\"$cluster|\", })",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "sum(ceph_pg_creating{cluster=~\"$cluster|\", })",
     "legendFormat": "Creating"
    },
    {
     "expr": "sum(ceph_pg_wait_backfill{cluster=~\"$cluster|\", })",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "sum(ceph_pg_deep{cluster=~\"$cluster|\", })",
     "legendFormat": "Deep"
    },
    {
     "expr": "sum(ceph_pg_scrubbing{cluster=~\"$cluster|\", })",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "sum(ceph_pg_recovering{cluster=~\"$cluster|\", })",
     "legendFormat": "Recovering"
    },
    {
     "expr": "sum(ceph_pg_repair{cluster=~\"$cluster|\", })",
     "legendFormat": "Repair"
    },
    {
     "expr": "sum(ceph_pg_down{cluster=~\"$cluster|\", })",
     "legendFormat": "Down"
    },
    {
     "expr": "sum(ceph_pg_peered{cluster=~\"$cluster|\", })",
     "legendFormat": "Peered"
    },
    {
     "expr": "sum(ceph_pg_backfill{cluster=~\"$cluster|\", })",
     "legendFormat": "Backfill"
    },
    {
     "expr": "sum(ceph_pg_remapped{cluster=~\"$cluster|\", })",
     "legendFormat": "Remapped"
    },
    {
     "expr": "sum(ceph_pg_backfill_toofull{cluster=~\"$cluster|\", })",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pg_degraded{cluster=~\"$cluster|\", })",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{cluster=~\"$cluster|\", })",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_pg_undersized{cluster=~\"$cluster|\", })",
     "legendFormat": "Undersized"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_recovery_ops{cluster=~\"$cluster|\", }[$__rate_interval]))",
     "legendFormat": "OPS"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSD Apply Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "ceph_osd_apply_latency_ms{cluster=~\"$cluster|\", }"
      }
     ]
    },
    {
     "title": "OSD Commit Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "ceph_osd_commit_latency_ms{cluster=~\"$cluster|\", }"
      }
     ]
    },
    {
     "title": "OSD Read Op Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) / rate(ceph_osd_op_r_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) >= 0"
      }
     ]
    },
    {
     "title": "OSD Write Op Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_w_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) / rate(ceph_osd_op_w_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) >= 0"
      }
     ]
    },
    {
     "title": "Recovery Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(rate(ceph_osd_op_r_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) / rate(ceph_osd_op_r_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) >= 0)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(ceph_osd_op_w_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) / rate(ceph_osd_op_w_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) >= 0)",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "AVG OSD Apply + Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(ceph_osd_apply_latency_ms{cluster=~\"$cluster|\", })",
       "legendFormat": "apply"
      },
      {
       "expr": "avg(ceph_osd_commit_latency_ms{cluster=~\"$cluster|\", })",
       "legendFormat": "commit"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Ceph Versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_osd_metadata{cluster=~\"$cluster|\", })",
     "legendFormat": "OSD Services"
    },
    {
     "expr": "count by (ceph_version)(ceph_mon_metadata{cluster=~\"$cluster|\", })",
     "legendFormat": "Mon Services"
    },
    {
     "expr": "count by (ceph_version)(ceph_mds_metadata{cluster=~\"$cluster|\", })",
     "legendFormat": "MDS Services"
    },
    {
     "expr": "count by (ceph_version)(ceph_rgw_metadata{cluster=~\"$cluster|\", })",
     "legendFormat": "RGW Services"
    },
    {
     "expr": "count by (ceph_version)(ceph_mgr_metadata{cluster=~\"$cluster|\", })",
     "legendFormat": "MGR Services"
    }
   ]
  }
 ]
}
{
 "title": "SMB Overview",
 "description": "SMB Overview dashboard shows data across all clusters and hosts associated with the SMB service.",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "SMBcluster",
    "label": "SMB Cluster",
    "query": "label_values(smb_metrics_status,netbiosname)"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "label_values(smb_metrics_status{netbiosname=~\"$SMBcluster\"},instance)"
   },
   {
    "name": "share",
    "label": "Share",
    "query": {
     "query": "label_values(smb_smb2_request_inbytes{netbiosname=~\"$SMBcluster\", instance=~\"$hostname\"},share)"
    }
   },
   {
    "name": "client",
    "label": "Client",
    "query": {
     "query": "label_values(smb_smb2_request_inbytes{netbiosname=~\"$SMBcluster\", instance=~\"$hostname\", share=~\"$share\"},client)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus SMB metrics status",
   "type": "stat",
   "description": "SMB metrics daemon health.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smb_metrics_status{instance=~\"$hostname\"})  by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of nodes per cluster/s",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (netbiosname) (smb_sessions_total * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "stat",
   "description": "Number of users currently logged in Cluster/s",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(netbiosname)(smb_sessions_total * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"}) / (count by ( netbiosname)(smb_sessions_total * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shares activity",
   "type": "stat",
   "description": "Number of remote machines using a share in cluster/s",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(netbiosname)(smb_share_activity * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"}) / (count by ( netbiosname)(smb_share_activity * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "stat",
   "description": "Number of currently active SMB user per cluster/s",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(netbiosname)(smb_users_total * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"}) / (count by ( netbiosname)(smb_users_total * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress throughtput",
   "type": "stat",
   "description": "Current total ingress throughput, bytes going in per second",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(smb_smb2_request_inbytes{instance=~\"$hostname\", share=~\"$share\", client=~\"$client\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "Current total request time for the sum of all runing operations",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(smb_smb2_request_duration_microseconds_sum{instance=~\"$hostname\", share=~\"$share\", client=~\"$client\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress throughtput",
   "type": "stat",
   "description": "Current total egress throughput, bytes going out per second",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(smb_smb2_request_outbytes{instance=~\"$hostname\", share=~\"$share\", client=~\"$client\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "stat",
   "description": "Current total number of operations per second",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(smb_smb2_request_total{instance=~\"$hostname\", share=~\"$share\", client=~\"$client\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput per Operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(smb_smb2_request_inbytes{instance=~\"$hostname\", share=~\"$share\", client=~\"$client\"}[$__rate_interval]))",
     "legendFormat": "Input - {{operation}}"
    },
    {
     "expr": "sum by (operation) (rate(smb_smb2_request_outbytes{instance=~\"$hostname\", share=~\"$share\", client=~\"$client\"}[$__rate_interval]))",
     "legendFormat": "Output-  {{operation}}"
    }
   ]
  },
  {
   "title": "IO per Operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(smb_smb2_request_total{instance=~\"$hostname\", share=~\"$share\", client=~\"$client\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Latencies per operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(smb_smb2_request_duration_microseconds_sum{instance=~\"$hostname\", share=~\"$share\", client=~\"$client\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}
{
 "title": "Ceph NVMe-oF Gateways - Overview",
 "description": "Ceph NVMe-oF gateways overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "group",
    "label": "Gateway Group",
    "query": "label_values(ceph_nvmeof_gateway_info,group)"
   },
   {
    "name": "gateway",
    "label": "Gateway Hostname",
    "query": "label_values(ceph_nvmeof_gateway_info{group=~'$group'},hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gateway Groups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count  by (group) (ceph_nvmeof_gateway_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Gateways",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_cephadm_daemon_status{service_type=\"nvmeof\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ceph_cephadm_daemon_status{service_type=\"nvmeof\"}==1 or ceph_cephadm_daemon_status{service_type=\"nvmeof\"}==2)",
     "legendFormat": "Available"
    },
    {
     "expr": "count(ceph_cephadm_daemon_status{service_type=\"nvmeof\"}==0 or ceph_cephadm_daemon_status{service_type=\"nvmeof\"}==-1 or ceph_cephadm_daemon_status{service_type=\"nvmeof\"} == -2)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Unhealthy Gateway Trend",
   "type": "timeseries",
   "description": "Gateways in error states",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "group by (daemon_name) (ceph_cephadm_daemon_status{service_type=\"nvmeof\"} == 0)",
     "legendFormat": "stopped - {{ daemon_name }} "
    },
    {
     "expr": "group by (daemon_name) (ceph_cephadm_daemon_status{service_type=\"nvmeof\"} == -1)",
     "legendFormat": "error - {{ daemon_name }}"
    },
    {
     "expr": "group by (daemon_name) (ceph_cephadm_daemon_status{service_type=\"nvmeof\"} == -2)",
     "legendFormat": "unknown_state - {{ daemon_name }}"
    }
   ]
  },
  { "title": "Active Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 } },
  {
   "title": "Gateways per group",
   "type": "piechart",
   "description": "Gateways in each group",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count  by (group) (ceph_nvmeof_gateway_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NVMeoF Group Overview -  $group",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Gateways",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_nvmeof_gateway_info{group=~'$group'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subsystems",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(nqn) (ceph_nvmeof_subsystem_metadata{group=~'$group',instance=~'$gateway'}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (bdev_name) (\n  ceph_nvmeof_bdev_metadata{instance=~'$gateway'} * on (instance) group_left(group) ceph_nvmeof_gateway_info{group=~'$group'}\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "description": "Average connected clients",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (nqn) (sum by(gw_name, nqn) (ceph_nvmeof_host_connection_state{instance=~'$gateway'} * on (instance) group_left(group) ceph_nvmeof_gateway_info{group=~'$group'}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity Exported",
   "type": "stat",
   "description": "The sum of capacity from all namespaces defined to subsystems",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg by (group) (sum by(group, instance) (ceph_nvmeof_bdev_capacity_bytes{instance=~'$gateway'} * on (instance) group_left(group) ceph_nvmeof_gateway_info{group=~'$group'})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subsystem Security",
   "type": "stat",
   "description": "WARNING if any subsystem is defined with open/no security",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_nvmeof_subsystem_metadata{allow_any_host='yes',group=~'$group', instance=~'$gateway'}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active gateways count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (group) (ceph_nvmeof_gateway_info{group=~'$group',instance=~'$gateway'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Busiest Gateway CPU",
   "type": "bargauge",
   "description": "Shows the highest average CPU on a gateway within the gateway group",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, avg by(instance) (rate(ceph_nvmeof_reactor_seconds_total{mode='busy',instance=~'$gateway'}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS - $gateway",
   "type": "stat",
   "description": "All gateways",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_nvmeof_bdev_reads_completed_total{instance=~'$gateway'}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(ceph_nvmeof_bdev_writes_completed_total{instance=~'$gateway'}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Throughput - $gateway",
   "type": "stat",
   "description": "All gateways",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(ceph_nvmeof_bdev_read_bytes_total{instance=~'$gateway'}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum (rate(ceph_nvmeof_bdev_written_bytes_total{instance=~'$gateway'}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Gateway Information",
   "type": "table",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "(count by(instance) (ceph_nvmeof_reactor_seconds_total{mode='busy'})) * on (instance) group_left(group,hostname,version,addr) ceph_nvmeof_gateway_info{group=~'$group'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Subsystems by Namespace",
   "type": "bargauge",
   "description": "Show the subsystems by the count of namespaces they present to the client",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, avg by (nqn) (ceph_nvmeof_subsystem_namespace_count{instance=~'$gateway'} * on (instance) group_left(group) ceph_nvmeof_gateway_info{group=~'$group'}))",
     "legendFormat": "{{nqn}}"
    }
   ]
  },
  {
   "title": "Top 5 Subsystems with Most Connected Clients",
   "type": "bargauge",
   "description": "Show the subsystems by the count of namespaces they present to the client",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, avg by (nqn) (sum by(gw_name, nqn) (ceph_nvmeof_host_connection_state{instance=~'$gateway'} * on (instance) group_left(group) ceph_nvmeof_gateway_info{group=~'$group'}))) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "OSD Overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Read Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  rate(ceph_osd_op_r_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) /\n  on (ceph_daemon) rate(ceph_osd_op_r_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) * 1000\n)\n",
     "legendFormat": "AVG read"
    },
    {
     "expr": "max(\n  rate(ceph_osd_op_r_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) /\n  on (ceph_daemon) rate(ceph_osd_op_r_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) * 1000\n)\n",
     "legendFormat": "MAX read"
    },
    {
     "expr": "quantile(0.95,\n  (\n    rate(ceph_osd_op_r_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) /\n    on (ceph_daemon) rate(ceph_osd_op_r_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) * 1000\n  )\n)\n",
     "legendFormat": "@95%ile"
    }
   ]
  },
  {
   "title": "Highest READ Latencies",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\n  (sort(\n    (\n      rate(ceph_osd_op_r_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) /\n        on (ceph_daemon) rate(ceph_osd_op_r_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) *\n        1000\n    )\n  ))\n)\n"
    }
   ]
  },
  {
   "title": "OSD Write Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  rate(ceph_osd_op_w_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) /\n  on (ceph_daemon) rate(ceph_osd_op_w_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) * 1000\n)\n",
     "legendFormat": "AVG write"
    },
    {
     "expr": "max(\n  rate(ceph_osd_op_w_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) /\n  on (ceph_daemon) rate(ceph_osd_op_w_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) * 1000\n)\n",
     "legendFormat": "MAX write"
    },
    {
     "expr": "quantile(0.95,\n  (\n    rate(ceph_osd_op_w_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) /\n    on (ceph_daemon) rate(ceph_osd_op_w_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) * 1000\n  )\n)\n",
     "legendFormat": "@95%ile write"
    }
   ]
  },
  {
   "title": "Highest WRITE Latencies",
   "type": "table",
   "description": "This table shows the osd's that are delivering the 10 highest write latencies within the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\n  (sort(\n    (rate(ceph_osd_op_w_latency_sum{cluster=~\"$cluster|\", }[$__rate_interval]) /\n      on (ceph_daemon) rate(ceph_osd_op_w_latency_count{cluster=~\"$cluster|\", }[$__rate_interval]) *\n      1000)\n  ))\n)\n"
    }
   ]
  },
  {
   "title": "OSD Types Summary",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by (device_class) (ceph_osd_metadata{cluster=~\"$cluster|\", })",
     "legendFormat": "{{device_class}}"
    }
   ]
  },
  {
   "title": "OSD Objectstore Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "count(ceph_bluefs_wal_total_bytes{cluster=~\"$cluster|\", })",
     "legendFormat": "bluestore"
    },
    {
     "expr": "absent(ceph_bluefs_wal_total_bytes{cluster=~\"$cluster|\", }) * count(ceph_osd_metadata{cluster=~\"$cluster|\", })",
     "legendFormat": "filestore"
    }
   ]
  },
  {
   "title": "OSD Size Summary",
   "type": "piechart",
   "description": "The pie chart shows the various OSD sizes used within the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "count(ceph_osd_stat_bytes{cluster=~\"$cluster|\", } < 1099511627776)",
     "legendFormat": "<1TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{cluster=~\"$cluster|\", } >= 1099511627776 < 2199023255552)",
     "legendFormat": "<2TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{cluster=~\"$cluster|\", } >= 2199023255552 < 3298534883328)",
     "legendFormat": "<3TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{cluster=~\"$cluster|\", } >= 3298534883328 < 4398046511104)",
     "legendFormat": "<4TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{cluster=~\"$cluster|\", } >= 4398046511104 < 6597069766656)",
     "legendFormat": "<6TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{cluster=~\"$cluster|\", } >= 6597069766656 < 8796093022208)",
     "legendFormat": "<8TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{cluster=~\"$cluster|\", } >= 8796093022208 < 10995116277760)",
     "legendFormat": "<10TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{cluster=~\"$cluster|\", } >= 10995116277760 < 13194139533312)",
     "legendFormat": "<12TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{cluster=~\"$cluster|\", } >= 13194139533312)",
     "legendFormat": "<12TB+"
    }
   ]
  },
  {
   "title": "Distribution of PGs per OSD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "# of OSDs" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_numpg{cluster=~\"$cluster|\", }",
     "legendFormat": "PGs per OSD"
    }
   ]
  },
  {
   "title": "OSD onode Hits Ratio",
   "type": "singlestat",
   "description": "This gauge panel shows onode Hits ratio to help determine if increasing RAM per OSD could help improve the performance of the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_bluestore_onode_hits{cluster=~\"$cluster|\", }) / (\n  sum(ceph_bluestore_onode_hits{cluster=~\"$cluster|\", }) +\n  sum(ceph_bluestore_onode_misses{cluster=~\"$cluster|\", })\n)\n"
    }
   ]
  },
  { "title": "R/W Profile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Read/Write Profile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(rate(ceph_pool_rd{cluster=~\"$cluster|\", }[$__rate_interval])))",
     "legendFormat": "Reads"
    },
    {
     "expr": "round(sum(rate(ceph_pool_wr{cluster=~\"$cluster|\", }[$__rate_interval])))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Top Slow Ops",
   "type": "table",
   "description": "This table shows the 10 OSDs with the highest number of slow ops",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "topk(10,\n  (ceph_daemon_health_metrics{type=\"SLOW_OPS\", ceph_daemon=~\"osd.*\"})\n)\n"
    }
   ]
  }
 ]
}
{
 "title": "Host Details",
 "tags": [
  "ceph-mixin",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "ceph_hosts",
    "query": "label_values({__name__=~\"ceph_.+_metadata\", cluster=~\"$cluster|\", }, hostname)"
   }
  ]
 },
 "panels": [
  { "title": "$ceph_hosts System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSDs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (ceph_daemon) (ceph_osd_metadata{cluster=~\"$cluster|\",  hostname=~\"$ceph_hosts\"}))"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (mode) (\n  rate(node_cpu{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\", mode=~\"(irq|nice|softirq|steal|system|user|iowait)\"}[$__rate_interval]) or\n  rate(node_cpu_seconds_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\", mode=~\"(irq|nice|softirq|steal|system|user|iowait)\"}[$__rate_interval])\n) / (\n  scalar(\n    sum(rate(node_cpu{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n    rate(node_cpu_seconds_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]))\n  ) * 100\n)\n",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\nnode_memory_MemFree_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\nnode_memory_MemTotal_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n",
     "legendFormat": "total"
    },
    {
     "expr": "(\n  node_memory_Cached{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n  node_memory_Cached_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n) + (\n  node_memory_Buffers{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n  node_memory_Buffers_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n) + (\n  node_memory_Slab{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n  node_memory_Slab_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n)\n",
     "legendFormat": "buffers/cache"
    },
    {
     "expr": "(\n  node_memory_MemTotal{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n  node_memory_MemTotal_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n) - (\n  (\n    node_memory_MemFree{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n    node_memory_MemFree_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n  ) + (\n    node_memory_Cached{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n    node_memory_Cached_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n  ) + (\n    node_memory_Buffers{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n    node_memory_Buffers_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n  ) + (\n    node_memory_Slab{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n    node_memory_Slab_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n  )\n)\n",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Network Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (device) (\n  rate(node_network_receive_bytes{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\",device!=\"lo\"}[$__rate_interval]) or\n  rate(node_network_receive_bytes_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\",device!=\"lo\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "sum by (device) (\n  rate(node_network_transmit_bytes{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\",device!=\"lo\"}[$__rate_interval]) or\n  rate(node_network_transmit_bytes_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\",device!=\"lo\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "Network drop rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\nrate(node_network_receive_drop_total{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval])\n",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "rate(node_network_transmit_drop{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\nrate(node_network_transmit_drop_total{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval])\n",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "Raw Capacity",
   "type": "singlestat",
   "description": "Each OSD consists of a Journal/WAL partition and a data partition. The RAW Capacity shown is the sum of the data partitions across all OSDs on the selected OSD hosts.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  ceph_osd_stat_bytes{cluster=~\"$cluster|\", } and\n    on (ceph_daemon) ceph_disk_occupation{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\", cluster=~\"$cluster|\", }\n)\n"
    }
   ]
  },
  {
   "title": "Network error rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\nrate(node_network_receive_errs_total{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval])\n",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "rate(node_network_transmit_errs{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\nrate(node_network_transmit_errs_total{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval])\n",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "OSD Disk Performance Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "$ceph_hosts Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(\n  (\n    rate(node_disk_writes_completed{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n    rate(node_disk_writes_completed_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval])\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) * on(instance, device) group_left(ceph_daemon) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{cluster=~\"$cluster|\", }, \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}}({{ceph_daemon}}) writes"
    },
    {
     "expr": "label_replace(\n  (\n    rate(node_disk_reads_completed{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n    rate(node_disk_reads_completed_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval])\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) * on(instance, device) group_left(ceph_daemon) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{cluster=~\"$cluster|\", }, \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}}({{ceph_daemon}}) reads"
    }
   ]
  },
  {
   "title": "$ceph_hosts Throughput by Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(\n  (\n    rate(node_disk_bytes_written{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n    rate(node_disk_written_bytes_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval])\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) * on(instance, device)\ngroup_left(ceph_daemon) label_replace(\n  label_replace(ceph_disk_occupation_human{cluster=~\"$cluster|\", }, \"device\", \"$1\", \"device\", \"/dev/(.*)\"),\n  \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}}({{ceph_daemon}}) write"
    },
    {
     "expr": "label_replace(\n  (\n    rate(node_disk_bytes_read{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n    rate(node_disk_read_bytes_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval])\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) * on(instance, device)\ngroup_left(ceph_daemon) label_replace(\n  label_replace(ceph_disk_occupation_human{cluster=~\"$cluster|\", }, \"device\", \"$1\", \"device\", \"/dev/(.*)\"),\n  \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}}({{ceph_daemon}}) read"
    }
   ]
  },
  {
   "title": "$ceph_hosts Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, device) (\n  label_replace(\n    (\n      (rate(node_disk_write_time_seconds_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval])) /\n      clamp_min(rate(node_disk_writes_completed_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]), 0.001) or\n      (rate(node_disk_read_time_seconds_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval])) /\n      clamp_min(rate(node_disk_reads_completed_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]), 0.001)\n    ),\n    \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n  )\n) * on(instance, device) group_left(ceph_daemon) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}}({{ceph_daemon}})"
    }
   ]
  },
  {
   "title": "$ceph_hosts Disk utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\n  (\n    (rate(node_disk_io_time_ms{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) / 10) or\n    rate(node_disk_io_time_seconds_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) * 100\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) * on(instance, device) group_left(ceph_daemon) label_replace(\n  label_replace(ceph_disk_occupation_human{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\", cluster=~\"$cluster|\", },\n  \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}}({{ceph_daemon}})"
    }
   ]
  },
  {
   "title": "Top Slow Ops per Host",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "topk(10,\n  (sum by (instance)(ceph_daemon_health_metrics{type=\"SLOW_OPS\", ceph_daemon=~\"osd.*\", cluster=~\"$cluster|\", }))\n)\n"
    }
   ]
  }
 ]
}
{
 "title": "MDS Performance",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "mds_servers",
    "label": "MDS Server",
    "query": "label_values(ceph_mds_inodes{cluster=~\"$cluster\", }, ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "MDS Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MDS Workload - $mds_servers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(ceph_objecter_op_r{ceph_daemon=~\"($mds_servers).*\", cluster=~\"$cluster\", }[$__rate_interval]))",
     "legendFormat": "Read Ops"
    },
    {
     "expr": "sum(rate(ceph_objecter_op_w{ceph_daemon=~\"($mds_servers).*\", cluster=~\"$cluster\", }[$__rate_interval]))",
     "legendFormat": "Write Ops"
    }
   ]
  },
  {
   "title": "Client Request Load - $mds_servers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ceph_mds_server_handle_client_request{ceph_daemon=~\"($mds_servers).*\", cluster=~\"$cluster\", }",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  }
 ]
}
{
 "title": "Ceph Pools Overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   { "name": "topk", "label": "TopK", "query": "15" }
  ]
 },
 "panels": [
  {
   "title": "Pools",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ceph_pool_metadata{cluster=~\"$cluster|\", })"
    }
   ]
  },
  {
   "title": "Pools with Compression",
   "type": "singlestat",
   "description": "Count of the pools that have compression enabled",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_pool_metadata{compression_mode!=\"none\", cluster=~\"$cluster|\", })"
    }
   ]
  },
  {
   "title": "Total Raw Capacity",
   "type": "singlestat",
   "description": "Total raw capacity available to the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes{cluster=~\"$cluster|\", })"
    }
   ]
  },
  {
   "title": "Raw Capacity Consumed",
   "type": "singlestat",
   "description": "Total raw capacity consumed by user data and associated overheads (metadata + redundancy)",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{cluster=~\"$cluster|\", })"
    }
   ]
  },
  {
   "title": "Logical Stored ",
   "type": "singlestat",
   "description": "Total of client data stored in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_pool_stored{cluster=~\"$cluster|\", })"
    }
   ]
  },
  {
   "title": "Compression Savings",
   "type": "singlestat",
   "description": "A compression saving is determined as the data eligible to be compressed minus the capacity used to store the data after compression",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  ceph_pool_compress_under_bytes{cluster=~\"$cluster|\", } -\n    ceph_pool_compress_bytes_used{cluster=~\"$cluster|\", }\n)\n"
    }
   ]
  },
  {
   "title": "Compression Eligibility",
   "type": "singlestat",
   "description": "Indicates how suitable the data is within the pools that are/have been enabled for compression - averaged across all pools holding compressed data",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  sum(ceph_pool_compress_under_bytes{cluster=~\"$cluster|\", } > 0) /\n    sum(ceph_pool_stored_raw{cluster=~\"$cluster|\", } and ceph_pool_compress_under_bytes{cluster=~\"$cluster|\", } > 0)\n) * 100\n"
    }
   ]
  },
  {
   "title": "Compression Factor",
   "type": "singlestat",
   "description": "This factor describes the average ratio of data eligible to be compressed divided by the data actually stored. It does not account for data written that was ineligible for compression (too small, or compression yield too low)",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  ceph_pool_compress_under_bytes{cluster=~\"$cluster|\", } > 0)\n    / sum(ceph_pool_compress_bytes_used{cluster=~\"$cluster|\", } > 0\n)\n"
    }
   ]
  },
  {
   "title": "Pool Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(\n  ceph_pool_compress_under_bytes{cluster=~\"$cluster|\", } /\n    ceph_pool_compress_bytes_used{cluster=~\"$cluster|\", } > 0\n) and on(pool_id) (\n  (\n    (ceph_pool_compress_under_bytes{cluster=~\"$cluster|\", } > 0) /\n      ceph_pool_stored_raw{cluster=~\"$cluster|\", }\n  ) * 100 > 0.5\n)\n",
     "legendFormat": "A"
    },
    {
     "expr": "ceph_pool_max_avail{cluster=~\"$cluster|\", } *\n  on(pool_id) group_left(name) ceph_pool_metadata{cluster=~\"$cluster|\", }\n",
     "legendFormat": "B"
    },
    {
     "expr": "(\n  (ceph_pool_compress_under_bytes{cluster=~\"$cluster|\", } > 0) /\n    ceph_pool_stored_raw{cluster=~\"$cluster|\", }\n) * 100\n",
     "legendFormat": "C"
    },
    {
     "expr": "ceph_pool_percent_used{cluster=~\"$cluster|\", } *\n  on(pool_id) group_left(name) ceph_pool_metadata{cluster=~\"$cluster|\", }\n",
     "legendFormat": "D"
    },
    {
     "expr": "ceph_pool_compress_under_bytes{cluster=~\"$cluster|\", } -\n  ceph_pool_compress_bytes_used{cluster=~\"$cluster|\", } > 0\n",
     "legendFormat": "E"
    },
    {
     "expr": "delta(ceph_pool_stored{cluster=~\"$cluster|\", }[5d])",
     "legendFormat": "F"
    },
    {
     "expr": "rate(ceph_pool_rd{cluster=~\"$cluster|\", }[$__rate_interval])\n  + rate(ceph_pool_wr{cluster=~\"$cluster|\", }[$__rate_interval])\n",
     "legendFormat": "G"
    },
    {
     "expr": "rate(ceph_pool_rd_bytes{cluster=~\"$cluster|\", }[$__rate_interval]) +\n  rate(ceph_pool_wr_bytes{cluster=~\"$cluster|\", }[$__rate_interval])\n",
     "legendFormat": "H"
    },
    {
     "expr": "ceph_pool_metadata{cluster=~\"$cluster|\", }",
     "legendFormat": "I"
    },
    {
     "expr": "ceph_pool_stored{cluster=~\"$cluster|\", } * on(pool_id) group_left ceph_pool_metadata{cluster=~\"$cluster|\", }",
     "legendFormat": "J"
    },
    {
     "expr": "ceph_pool_metadata{compression_mode!=\"none\", cluster=~\"$cluster|\", }",
     "legendFormat": "K"
    },
    { "legendFormat": "L" }
   ]
  },
  {
   "title": "Top $topk Client IOPS by Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($topk,\n  round(\n    (\n      rate(ceph_pool_rd{cluster=~\"$cluster|\", }[$__rate_interval]) +\n      rate(ceph_pool_wr{cluster=~\"$cluster|\", }[$__rate_interval])\n    ), 1\n  ) * on(pool_id) group_left(instance,name) ceph_pool_metadata{cluster=~\"$cluster|\", }\n)\n",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "topk($topk,\n  rate(ceph_pool_wr{cluster=~\"$cluster|\", }[$__rate_interval]) +\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{cluster=~\"$cluster|\", }\n)\n",
     "legendFormat": "{{name}} - write"
    }
   ]
  },
  {
   "title": "Top $topk Client Bandwidth by Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk($topk,\n  (\n    rate(ceph_pool_rd_bytes{cluster=~\"$cluster|\", }[$__rate_interval]) +\n    rate(ceph_pool_wr_bytes{cluster=~\"$cluster|\", }[$__rate_interval])\n  ) * on(pool_id) group_left(instance, name) ceph_pool_metadata{cluster=~\"$cluster|\", }\n)\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Capacity Usage (RAW)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_pool_bytes_used{cluster=~\"$cluster|\", } * on(pool_id) group_right ceph_pool_metadata{cluster=~\"$cluster|\", }",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}