{
 "title": "File Systems",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Network drives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage time series",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "1 - (node_filesystem_avail_bytes{fstype=~\"cifs|nfs4\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info{nodename=\"at-compute010\"}) \n/ \n(node_filesystem_size_bytes{fstype=~\"cifs|nfs4\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info{nodename=\"at-compute010\"})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Proportion used",
     "type": "bargauge",
     "gridPos": { "h": 57, "w": 11, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1 - (node_filesystem_avail_bytes{fstype=~\"cifs|nfs4\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info{nodename=\"at-compute010\"}) \n/ \n(node_filesystem_size_bytes{fstype=~\"cifs|nfs4\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info{nodename=\"at-compute010\"})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Total size (TB)",
     "type": "stat",
     "gridPos": { "h": 57, "w": 11, "x": 11, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{fstype=~\"cifs|nfs4\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info{nodename=\"at-compute010\"}) / 1024^4",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Direct-attached storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "/mnt/md0",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 166 },
     "targets": [
      {
       "expr": "1 - (node_filesystem_avail_bytes{mountpoint=\"/mnt/md0\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info) \n/ \n(node_filesystem_size_bytes{mountpoint=\"/mnt/md0\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Total size (GB)",
     "type": "stat",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 174 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{mountpoint=\"/mnt/md0\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info) / 1024^3",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Root file system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Root \"/\"",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 591 },
     "targets": [
      {
       "expr": "1 - (node_filesystem_avail_bytes{mountpoint=\"/\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info) \n/ \n(node_filesystem_size_bytes{mountpoint=\"/\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Total size (GB)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 600 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{mountpoint=\"/\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info) / 1024^3",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  }
 ]
}